name: Cache Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-4a6bb77

      - name: prime-cache-4a6bb77
        run: |
          if [ -n "${{ steps.cache-step.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi